### ISSUE TITLE
suggestion plan for firefox 57* webextension?

### ISSUE THREAD

**Issue by Zitronella** [AykutCevik/IDN-Safe#4] opened 2017-08-18 16:21 UTC
Hi, i tested your IDN-Safe in Chrome, but mostly i use Firefox. I signed your extension for my private and installed it in firefox. Generally it works and shows a red icon during punycode adress. 
But, it shows not this blue "1" in the icon, and not the real adress in adressbar and browsertab and so i can not reload the page. In chrome all works perfect.

Please please, would you make a full compatible firefox webextension? it would be really great! It exist no such extension on https://addons.mozilla.org/ as a webextension and i think such a extension would be very necessary and needed and IDN-Safe is the best i found in the web ;)
![idn-safe-chrome](https://user-images.githubusercontent.com/14326582/29467652-80ba5e44-8441-11e7-8266-a2461be92550.png)
![idn-safe-firefox](https://user-images.githubusercontent.com/14326582/29467657-85e539c0-8441-11e7-8cb0-878429f465ba.png)
Greetings (and sorry for my bad english)

**Comment by AykutCevik** [comment] 2017-08-25 11:03
Thank you for your detailed message @Zitronella!
The punycode view of the address is caused by Chrome itself. It is not a feature of the extension since the extension cannot write text to the address bar. 
This may be a setting in Firefox too.

As you can see in your Firefox screenshot the count of blocked items is above the icon and it is in red - I should change its color of course.

I'm already in the release process of the Firefox WebExtension but I'm stuck due to a bug, which you can [view here](https://github.com/mozilla/addons/issues/382).

I will close this issue when the extension is released so you will be notified then ;)

**Comment by AykutCevik** [comment] 2017-12-03 15:16
@Zitronella I was now able to make a release with a [workaround](https://github.com/mozilla/addons/issues/382#issuecomment-348780954). You can finally find the extension on the addons page of firefox: https://addons.mozilla.org/en-US/firefox/addon/idn-safe/

**Closed by AykutCevik** 2017-12-03 15:16 UTC
Labels: enhancement
